CREATE TABLE IF NOT EXISTS %%PREFIX%%boo_items_mod (
  `id` int(11) NOT NULL,
  `name` varchar(60) NOT NULL,
  `item_info_id` varchar(100) NOT NULL,
  `short_desc` varchar(80) NOT NULL,
  `type_id` int(12) NOT NULL,
  `url_website` varchar(255) NOT NULL,
  `url_repo` varchar(255) NOT NULL,
  `author` varchar(80) NOT NULL,
  `item_by` int(12) NOT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `edited` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `item_by` (`item_by`),
  KEY `type_id` (`type_id`),
  KEY `status` (`status`),
  KEY `created` (`created`),
  KEY `modified` (`modified`) ,
  KEY `edited` (`edited`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS %%PREFIX%%boo_versions_mod (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `item_id` int(12) NOT NULL,
  `status` int(1) NOT NULL,
  `version_name` varchar(80) NOT NULL,
  `last_changes` varchar(255) NOT NULL,
  `stability` enum('pre-alpha','alpha','stable','mature') NOT NULL DEFAULT 'stable',
  `filename` varchar(80) NOT NULL,
  `download_url` varchar(255) NOT NULL,
  `created` datetime DEFAULT NULL,
  `edited` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `item_id` (`item_id`),
  KEY `status` (`status`),
  KEY `created` (`created`),
  KEY `edited` (`edited`),
  KEY `modified` (`modified`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
