;<?php die(''); ?>
; for security reasons , don't remove or modify the first line
; don't modify this file if you don't know what you do. it is generated automatically by jInstaller
[index]
jelix.installed=1
jelix.version=1.3pre.1902
jacl2db.installed=1
jacl2db.version=1.3a3
jacldb.installed=0
jacldb.version=
jauth.installed=1
jauth.version=1.2
jauthdb.installed=0
jauthdb.version=
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
booster.installed=1
booster.version=0.1pre
jtags.installed=1
jtags.version=0.2
jcommunity.installed=1
jcommunity.version=0.2.1
jacl2db_admin.installed=0
jacl2db_admin.version=
jauthdb_admin.installed=0
jauthdb_admin.version=
master_admin.installed=0
master_admin.version=
boosteradmin.installed=1
boosteradmin.version=0.1pre
[__modules_data]
jelix.contexts="db:default"
jcommunity.contexts="index/auth.coord.ini.php,db:default,adminboost/auth.coord.ini.php"
jtags.contexts="db:default"
jacl2db.contexts="jacl2:index/jacl2.coord.ini.php,db:jacl2_profile,jacl2:adminboost/jacl2.coord.ini.php,jacl2:admin/jacl2.coord.ini.php"
booster.contexts=
jauth.contexts="auth:adminboost/auth.coord.ini.php,auth:admin/auth.coord.ini.php"
master_admin.contexts=
jauthdb.contexts="adminboost/auth.coord.ini.php,db:default,admin/auth.coord.ini.php"
jauthdb_admin.contexts="adminboost/auth.coord.ini.php,admin/auth.coord.ini.php"
[adminboost]
jelix.installed=1
jelix.version=1.3pre.1902
jacl2db.installed=1
jacl2db.version=1.3a3
jacldb.installed=0
jacldb.version=
jauth.installed=1
jauth.version=1.2
jauthdb.installed=1
jauthdb.version=1.2
junittests.installed=0
junittests.version=
jWSDL.installed=0
jWSDL.version=
booster.installed=1
booster.version=0.1pre
jcommunity.installed=1
jcommunity.version=0.2.1
jtags.installed=1
jtags.version=

jacl2db_admin.installed=1
jacl2db_admin.version=1.2
jauthdb_admin.installed=1
jauthdb_admin.version=1.2
master_admin.installed=1
master_admin.version=1.2

boosteradmin.installed=1
boosteradmin.version=0.1pre
